FROM alpine:edge
RUN apk update && apk add \
        strace \
        labwc dbus dbus-x11 \
        font-noto-cjk font-dejavu \
        icu-data-full \
        mesa-utils \
        fcitx5 fcitx5-gtk fcitx5-qt fcitx5-configtool libgee \
        pavucontrol-qt xterm \
        libdbusmenu-lxqt libfm-qt liblxqt libqtxdg libsysstat lxqt-about \
        lxqt-admin lxqt-archiver lxqt-config lxqt-globalkeys \
        lxqt-notificationd lxqt-openssh-askpass lxqt-panel \
        lxqt-policykit lxqt-powermanagement lxqt-qtplugin \
        lxqt-runner lxqt-sudo lxqt-themes \
        openbox pcmanfm-qt pm-utils qterminal qtermwidget xdg-utils \
        adwaita-qt oxygen \
        xscreensaver swaybg wlopm libnotify waybar font-awesome \
        docker-cli

